import type { Metadata } from "next";
import "./globals.css";

import ThemeProvider from "./components/providers/theme-provider";

export const metadata: Metadata = {
  title: "Dormie",
  authors: {
    name: "Waffen Sultan",
    url: "https://github.com/waffenffs"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <ThemeProvider attribute="class" defaultTheme="light">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
