import type { Metadata } from "next";

import { createClient } from "@/supabase/server"

import { Fragment } from "react";
import ListingsPage from "./page"

export const metadata: Metadata = {
    title: "Dormie - Listings",
    authors: {
        name: "Waffen Sultan",
        url: "https://github.com/waffenffs"
    },
    description: "Generated by create next app",
}

export default async function ListingsLayout() {
    const supabase = createClient();

    const { data } = await supabase.auth.getUser();

    const { data: userRoleData } = await supabase
        .from('users')
        .select('role_initialized')
        .eq('id', data.user?.id)
        .single()

    return (
        <Fragment>
            <ListingsPage 
                user={data?.user} 
                role_initialized={userRoleData?.role_initialized} 
            />
        </Fragment>
    )
}